- name: Ansible Copy WAR File Local to Remote
  hosts: 34.230.44.252
  tasks:
    - name: copying file with playbook
      become: true
      copy:
        src: ./target/sample-web.war
        dest: /opt/apache-tomcat-9.0.74/webapps
